"use client"; // Add this directive to make this a client component

import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/landingpage/sections/Navbar";
import { usePathname } from "next/navigation"; // Import from next/navigation

const primaryFont = Instrument_Sans({
  subsets: ["latin"],
  display: "swap",
});


// export const metadata = {
//   title: "BloodLink",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname(); // Use usePathname to get the current path

  return (
    <html lang="en">
      <body className={primaryFont.className}>
        {/* Conditionally render Navbar based on the current route */}
        {pathname !== '/signup' && pathname !== '/login' && <Navbar />}
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
