import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/landingpage/sections/Navbar";

const primaryFont = Instrument_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "BloodLink",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={primaryFont.className}
      >
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
